services:
  - type: web
    name: lekhaslides-backend
    env: python
    region: singapore
    plan: free
    buildCommand: "pip install -r backend/requirements.txt"
    startCommand: "cd backend && gunicorn main:app -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT"
    envVars:
      - key: GOOGLE_API_KEY
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.0

  - type: web
    name: lekhaslides-frontend
    env: static
    region: singapore
    plan: free
    buildCommand: "cd frontend && npm install && npm run build"
    staticPublishPath: ./frontend/dist
    envVars:
      - key: VITE_API_URL
        value: https://lekhaslides-backend.onrender.com
